name: GitHub Release

on: 
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0

    - name: Create release
      uses: ncipollo/release-action@v1
      if: ${{ github.event.base_ref == 'refs/heads/main' }}
      with:
        artifacts: "release.tar.gz,*.jar"
        bodyFile: "release.md"
        token: ${{ secrets.GITHUB_TOKEN }}