name: Maven Package

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: vars
      name: Setup environment variables      
      run: |
        echo "::set-output name=sha8::$(echo ${{ github.sha }} | cut -c1-8)"

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode package --file pom.xml "-Dartifact.version=${{ steps.vars.outputs.sha8 }}"
